# -*- coding: utf-8 -*-
"""RL_Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOZuw1-U-7rl-FjOSDN1vXjCny_RujUx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def plot_value_heatmap(mdp, V, title="Value Function Heatmap"):
    grid = V.reshape((mdp.n_rows, mdp.n_cols))
    plt.figure(figsize=(5, 4))
    plt.imshow(grid, cmap='viridis', origin='upper')
    plt.title(title)
    for i in range(mdp.n_rows):
        for j in range(mdp.n_cols):
            s = mdp.coord_to_state(i, j)
            plt.text(j, i, f"{V[s]:.2f}", ha='center', va='center', color='white', fontsize=9)
    plt.colorbar()
    plt.axis('off')
    plt.show()


def plot_policy_arrows(mdp, policy, title="Policy (Arrows)"):
    action_to_vec = {0: (-1, 0), 1: (0, 1), 2: (1, 0), 3: (0, -1)}
    U = np.zeros((mdp.n_rows, mdp.n_cols))
    Vv = np.zeros((mdp.n_rows, mdp.n_cols))

    plt.figure(figsize=(5, 4))
    plt.title(title)

    for s in range(mdp.n_states):
        r, c = mdp.state_to_coord(s)
        if s in mdp.terminals:
            plt.text(c, r, "T", ha='center', va='center', fontsize=12, color='red', fontweight='bold')
            continue
        best_action = np.argmax(policy[s])
        dr, dc = action_to_vec[best_action]
        U[r, c] = dc
        Vv[r, c] = -dr

    plt.quiver(np.arange(mdp.n_cols), np.arange(mdp.n_rows), U, Vv, angles='xy', scale_units='xy', scale=1)
    plt.gca().invert_yaxis()
    plt.axis('off')
    plt.show()


# ----------------------------------------------
# Step 6: Run and Visualize
# ----------------------------------------------
mdp = GridWorld()
final_policy, final_V = policy_iteration(mdp, gamma=1.0)

# Print results
print("\nFinal Value Function:")
print(final_V.reshape(mdp.n_rows, mdp.n_cols))

# Show heatmap & arrows
plot_value_heatmap(mdp, final_V, title="Final Value Function (4x4 Gridworld)")
plot_policy_arrows(mdp, final_policy, title="Final Policy Arrows")

# Save values to CSV
df = pd.DataFrame({
    "State": np.arange(mdp.n_states),
    "Value": final_V
})
df.to_csv("final_values_gridworld.csv", index=False)
print("\n✅ Final values saved as 'final_values_gridworld.csv'")