# -*- coding: utf-8 -*-
"""RL_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4JJYz90GHCVuV75862Oa3AllM-NLVuO
"""

import numpy as np
import matplotlib.pyplot as plt

# Define ad slots (arms of the bandit)
ad_slots = ["Top Banner", "Sidebar", "Footer", "Pop-up"]

# True click-through rates (CTR) for simulation (unknown to the algorithm)
# You can tweak these values to test different scenarios
true_ctrs = [0.04, 0.06, 0.02, 0.08]

# Parameters
epsilon = 0.1   # 10% exploration
n_impressions = 1000

# Tracking variables
n = len(ad_slots)
counts = np.zeros(n)           # number of times each slot was chosen
estimated_ctrs = np.zeros(n)   # estimated CTRs
rewards = []                   # reward history (clicks)

# Epsilon-Greedy algorithm
for i in range(n_impressions):
    # Exploration vs Exploitation
    if np.random.rand() < epsilon:
        choice = np.random.randint(n)  # Explore random slot
    else:
        choice = np.argmax(estimated_ctrs)  # Exploit best slot so far

    # Simulate user click (reward = 1 if clicked, 0 otherwise)
    reward = np.random.rand() < true_ctrs[choice]
    reward = int(reward)

    # Update counts and estimated CTR
    counts[choice] += 1
    estimated_ctrs[choice] += (reward - estimated_ctrs[choice]) / counts[choice]

    # Store reward
    rewards.append(reward)

# Results
print("True CTRs:", dict(zip(ad_slots, true_ctrs)))
print("Estimated CTRs:", dict(zip(ad_slots, np.round(estimated_ctrs, 3))))
print("Ad slot selection counts:", dict(zip(ad_slots, counts.astype(int))))
print("Total Clicks:", sum(rewards))

# Plot results
plt.figure(figsize=(14,5))

# CTR estimates
plt.subplot(1,2,1)
plt.bar(ad_slots, estimated_ctrs, color='skyblue', alpha=0.8, label="Estimated CTR")
plt.bar(ad_slots, true_ctrs, color='orange', alpha=0.4, label="True CTR")
plt.ylabel("CTR")
plt.title("True vs Estimated CTRs")
plt.legend()

# Cumulative reward
plt.figure(figsize=(14,5))
plt.subplot(1,2,2)
plt.plot(np.cumsum(rewards), label="Cumulative Clicks")
plt.xlabel("Impressions")
plt.ylabel("Total Clicks")
plt.title("Cumulative Reward Over Time")
plt.legend()

plt.tight_layout()
plt.show()